name: sticky_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  get_it: 7.7.0
  flutter_sticky_header: 0.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/
